//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1022
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CddaX.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CddaX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (best quality) ähnelt.
        /// </summary>
        internal static string BestQualitySuffix {
            get {
                return ResourceManager.GetString("BestQualitySuffix", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon ClearIcon {
            get {
                object obj = ResourceManager.GetObject("ClearIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon HelpIcon {
            get {
                object obj = ResourceManager.GetObject("HelpIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Initializing... ähnelt.
        /// </summary>
        internal static string InitializingMessage {
            get {
                return ResourceManager.GetString("InitializingMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon LeaveIcon {
            get {
                object obj = ResourceManager.GetObject("LeaveIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading metadata from MusicBrainz... ähnelt.
        /// </summary>
        internal static string LoadingMetadataStatusLabel {
            get {
                return ResourceManager.GetString("LoadingMetadataStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading table of contents... ähnelt.
        /// </summary>
        internal static string LoadingTocStatusLabel {
            get {
                return ResourceManager.GetString("LoadingTocStatusLabel", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon LogoIcon {
            get {
                object obj = ResourceManager.GetObject("LogoIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon MusicBrainzIcon {
            get {
                object obj = ResourceManager.GetObject("MusicBrainzIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No CD drive found :( ähnelt.
        /// </summary>
        internal static string NoCdDriveFoundStatusLabel {
            get {
                return ResourceManager.GetString("NoCdDriveFoundStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No CD inserted ähnelt.
        /// </summary>
        internal static string NoCdInsertedStatusLabel {
            get {
                return ResourceManager.GetString("NoCdInsertedStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ready ({0} tracks) ähnelt.
        /// </summary>
        internal static string ReadyStatusLabel {
            get {
                return ResourceManager.GetString("ReadyStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (recommended) ähnelt.
        /// </summary>
        internal static string RecommendedSuffix {
            get {
                return ResourceManager.GetString("RecommendedSuffix", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon RefreshIcon {
            get {
                object obj = ResourceManager.GetObject("RefreshIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rip completed successfully ähnelt.
        /// </summary>
        internal static string RipCompleteMessage {
            get {
                return ResourceManager.GetString("RipCompleteMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon SaveIcon {
            get {
                object obj = ResourceManager.GetObject("SaveIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saving cover image... ähnelt.
        /// </summary>
        internal static string SavingCoverMessage {
            get {
                return ResourceManager.GetString("SavingCoverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Success ähnelt.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Track {0} ähnelt.
        /// </summary>
        internal static string TrackNoMessage {
            get {
                return ResourceManager.GetString("TrackNoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown Album ähnelt.
        /// </summary>
        internal static string UnknownAlbum {
            get {
                return ResourceManager.GetString("UnknownAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown Artist ähnelt.
        /// </summary>
        internal static string UnknownArtist {
            get {
                return ResourceManager.GetString("UnknownArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown Composer ähnelt.
        /// </summary>
        internal static string UnknownComposer {
            get {
                return ResourceManager.GetString("UnknownComposer", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon WebIcon {
            get {
                object obj = ResourceManager.GetObject("WebIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (worst quality) ähnelt.
        /// </summary>
        internal static string WorstQualitySuffix {
            get {
                return ResourceManager.GetString("WorstQualitySuffix", resourceCulture);
            }
        }
    }
}
